server:
  port: 8082  # API(8080), Batch(8081)와 다른 포트 사용
spring:
  profiles:
    active: dev
  application:
    name: admin
  config:
    import:
      - "classpath:application-core.yaml"

logging:
  level:
    kr.co.prosafe.admin: DEBUG
    kr.co.prosafe.core: INFO
