AWSTemplateFormatVersion: '2010-09-09'

Description:
  'ECS IaC'

Parameters:
  ProjectName:
    Type: String
  ENV:
    Type: String
    AllowedValues:
      - dev
      - prod

Conditions:
  IsProd: !Equals [!Ref ENV, 'prod']

Resources:
  # Secret Manager
  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/${ENV}/spring'
      GenerateSecretString:
        SecretStringTemplate: !Sub '{}'
        GenerateStringKey: 'key'
        PasswordLength: 50
        ExcludeCharacters: '"@/\&;='
  # ECS Cluster
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub '${ProjectName}-${ENV}-ecs-cluster'
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub '${ProjectName}-${ENV}-ecs-cluster-sg'
      VpcId: {'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-VPC'}
  SecurityGroupInboundSSH:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      CidrIp: 0.0.0.0/0
  SecurityGroupInboundHTTP:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SecurityGroup
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      CidrIp: 0.0.0.0/0
  SecurityGroupInboundHTTPS:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SecurityGroup
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      CidrIp: 0.0.0.0/0
  SecurityGroupInboundALB:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SecurityGroup
      IpProtocol: tcp
      FromPort: 8080
      ToPort: 8081
      SourceSecurityGroupId: !Ref SecurityGroup
  ServiceAutoscalingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [application-autoscaling.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: service-autoscaling
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'application-autoscaling:*'
                  - 'cloudwatch:DescribeAlarms'
                  - 'cloudwatch:PutMetricAlarm'
                  - 'ecs:DescribeServices'
                  - 'ecs:UpdateService'
                Resource: '*'
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${ProjectName}-${ENV}-alb'
      Type: application
      IpAddressType: ipv4
      Scheme: internet-facing
      Subnets:
        - {'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-PublicSubnet1'}
        - {'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-PublicSubnet2'}
      SecurityGroups: [!Ref SecurityGroup]
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: 15
  # Target Groups for each module
  ALBTargetGroupAdmin:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: ALB
    Properties:
      HealthCheckIntervalSeconds: 5
      HealthCheckPath: /actuator/health
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 2
      HealthyThresholdCount: 2
      Name: !Sub '${ProjectName}-${ENV}-tg-admin'
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      UnhealthyThresholdCount: 2
      VpcId: {'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-VPC'}
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 5
  ALBTargetGroupApi:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: ALB
    Properties:
      HealthCheckIntervalSeconds: 5
      HealthCheckPath: /actuator/health
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 2
      HealthyThresholdCount: 2
      Name: !Sub '${ProjectName}-${ENV}-tg-api'
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      UnhealthyThresholdCount: 2
      VpcId: {'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-VPC'}
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 5
  ALBTargetGroupBatch:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: ALB
    Properties:
      HealthCheckIntervalSeconds: 5
      HealthCheckPath: /actuator/health
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 2
      HealthyThresholdCount: 2
      Name: !Sub '${ProjectName}-${ENV}-tg-batch'
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      UnhealthyThresholdCount: 2
      VpcId: {'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-VPC'}
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 5
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroupApi
  # Listener Rules for path-based routing
  ALBListenerRuleAdmin:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    DependsOn: ALBListener
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroupAdmin
      Conditions:
        - Field: path-pattern
          Values: ['/admin*']
      ListenerArn: !Ref ALBListener
      Priority: 1
  ALBListenerRuleApi:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    DependsOn: ALBListener
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroupApi
      Conditions:
        - Field: path-pattern
          Values: ['/api*']
      ListenerArn: !Ref ALBListener
      Priority: 2
  ALBListenerRuleBatch:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    DependsOn: ALBListener
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroupBatch
      Conditions:
        - Field: path-pattern
          Values: ['/batch*']
      ListenerArn: !Ref ALBListener
      Priority: 3
  TaskDefinitionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${ProjectName}/${ENV}'
      RetentionInDays: 14

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ ecs-tasks.amazonaws.com ]
            Action: [ 'sts:AssumeRole' ]
      Path: /
      Policies:
        - PolicyName: ecs-task
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:GetRepositoryPolicy'
                  - 'ecr:DescribeRepositories'
                  - 'ecr:ListImages'
                  - 'ecr:DescribeImages'
                  - 'ecr:BatchGetImage'
                  - 'ecr:GetLifecyclePolicy'
                  - 'ecr:GetLifecyclePolicyPreview'
                  - 'ecr:ListTagsForResource'
                  - 'ecr:DescribeImageScanFindings'
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:DeleteLogStream'
                  - 'logs:DescribeLogStreams'
                  - 'logs:PutLogEvents'
                  - 'logs:PutRetentionPolicy'
                  - 'xray:*'
                  - 's3:*'
                  - 'sqs:*'
                  - 'secretsmanager:GetResourcePolicy'
                  - 'secretsmanager:GetSecretValue'
                  - 'secretsmanager:DescribeSecret'
                  - 'secretsmanager:ListSecretVersionIds'
                  - 'secretsmanager:ListSecrets'
                Resource: '*'
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${ENV}-execution-role'
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'

  # Admin Module
  TaskDefinitionAdmin:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${ProjectName}-${ENV}-admin-family'
      TaskRoleArn: !GetAtt TaskRole.Arn
      ExecutionRoleArn: !Ref ExecutionRole
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 1 vCPU
      Memory: 2GB
      ContainerDefinitions:
        - Name: admin
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ProjectName}-admin:${ENV}'
          Essential: true
          StopTimeout: 5
          PortMappings:
            - ContainerPort: 8080
          Environment:
            - Name: SPRING_PROFILES_ACTIVE
              Value: !Ref ENV
            - Name: ECS_IMAGE_PULL_BEHAVIOR
              Value: prefer-cached
          EntryPoint: ["java","-jar","/app.jar"]
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref TaskDefinitionLogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: /ecs/admin
  # API Module
  TaskDefinitionApi:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${ProjectName}-${ENV}-api-family'
      TaskRoleArn: !GetAtt TaskRole.Arn
      ExecutionRoleArn: !Ref ExecutionRole
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 1 vCPU
      Memory: 2GB
      ContainerDefinitions:
        - Name: api
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ProjectName}-api:${ENV}'
          Essential: true
          StopTimeout: 5
          PortMappings:
            - ContainerPort: 8080
          Environment:
            - Name: SPRING_PROFILES_ACTIVE
              Value: !Ref ENV
            - Name: ECS_IMAGE_PULL_BEHAVIOR
              Value: prefer-cached
          EntryPoint: ["java","-jar","/app.jar"]
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref TaskDefinitionLogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: /ecs/api
  # Batch Module
  TaskDefinitionBatch:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${ProjectName}-${ENV}-batch-family'
      TaskRoleArn: !GetAtt TaskRole.Arn
      ExecutionRoleArn: !Ref ExecutionRole
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 1 vCPU
      Memory: 2GB
      ContainerDefinitions:
        - Name: batch
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ProjectName}-batch:${ENV}'
          Essential: true
          StopTimeout: 5
          PortMappings:
            - ContainerPort: 8080
          Environment:
            - Name: SPRING_PROFILES_ACTIVE
              Value: !Ref ENV
            - Name: ECS_IMAGE_PULL_BEHAVIOR
              Value: prefer-cached
          EntryPoint: ["java","-jar","/app.jar"]
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref TaskDefinitionLogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: /ecs/batch
  # Services for each module
  ServiceAdmin:
    Type: AWS::ECS::Service
    DependsOn: ALBListenerRuleAdmin
    Properties:
      Cluster: !Ref Cluster
      LaunchType: FARGATE
      ServiceName: admin
      TaskDefinition: !Ref TaskDefinitionAdmin
      HealthCheckGracePeriodSeconds: 120
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !If [ IsProd, { 'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-PrivateSubnet1' }, { 'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-PublicSubnet1' } ]
            - !If [ IsProd, { 'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-PrivateSubnet2' }, { 'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-PublicSubnet2' } ]
          SecurityGroups: [!Ref SecurityGroup]
      LoadBalancers:
        - ContainerName: admin
          ContainerPort: 8080
          TargetGroupArn: !Ref ALBTargetGroupAdmin
  ServiceApi:
    Type: AWS::ECS::Service
    DependsOn: ALBListenerRuleApi
    Properties:
      Cluster: !Ref Cluster
      LaunchType: FARGATE
      ServiceName: api
      TaskDefinition: !Ref TaskDefinitionApi
      HealthCheckGracePeriodSeconds: 120
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !If [ IsProd, { 'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-PrivateSubnet1' }, { 'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-PublicSubnet1' } ]
            - !If [ IsProd, { 'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-PrivateSubnet2' }, { 'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-PublicSubnet2' } ]
          SecurityGroups: [!Ref SecurityGroup]
      LoadBalancers:
        - ContainerName: api
          ContainerPort: 8080
          TargetGroupArn: !Ref ALBTargetGroupApi
  ServiceBatch:
    Type: AWS::ECS::Service
    DependsOn: ALBListenerRuleBatch
    Properties:
      Cluster: !Ref Cluster
      LaunchType: FARGATE
      ServiceName: batch
      TaskDefinition: !Ref TaskDefinitionBatch
      HealthCheckGracePeriodSeconds: 120
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !If [ IsProd, { 'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-PrivateSubnet1' }, { 'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-PublicSubnet1' } ]
            - !If [ IsProd, { 'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-PrivateSubnet2' }, { 'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-PublicSubnet2' } ]
          SecurityGroups: [!Ref SecurityGroup]
      LoadBalancers:
        - ContainerName: batch
          ContainerPort: 8080
          TargetGroupArn: !Ref ALBTargetGroupBatch
  # Auto Scaling for each service
  ServiceScalingTargetAdmin:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: ServiceAdmin
    Properties:
      MinCapacity: 1
      MaxCapacity: 3
      ResourceId: !Join ['/', [service, !Ref Cluster, !GetAtt ServiceAdmin.Name]]
      RoleARN: !GetAtt ServiceAutoscalingRole.Arn
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
  ServiceScalingPolicyAdmin:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub '${ProjectName}-${ENV}-asg-policy-admin'
      ScalingTargetId: !Ref ServiceScalingTargetAdmin
      PolicyType: TargetTrackingScaling
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ALBRequestCountPerTarget
          ResourceLabel: !Join ['/', [!GetAtt ALB.LoadBalancerFullName, !GetAtt ALBTargetGroupAdmin.TargetGroupFullName]]
        TargetValue: 1000
        ScaleInCooldown: 30
        ScaleOutCooldown: 30
  ServiceScalingTargetApi:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: ServiceApi
    Properties:
      MinCapacity: 1
      MaxCapacity: 5
      ResourceId: !Join ['/', [service, !Ref Cluster, !GetAtt ServiceApi.Name]]
      RoleARN: !GetAtt ServiceAutoscalingRole.Arn
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
  ServiceScalingPolicyApi:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub '${ProjectName}-${ENV}-asg-policy-api'
      ScalingTargetId: !Ref ServiceScalingTargetApi
      PolicyType: TargetTrackingScaling
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ALBRequestCountPerTarget
          ResourceLabel: !Join ['/', [!GetAtt ALB.LoadBalancerFullName, !GetAtt ALBTargetGroupApi.TargetGroupFullName]]
        TargetValue: 1000
        ScaleInCooldown: 30
        ScaleOutCooldown: 30
  ServiceScalingTargetBatch:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: ServiceBatch
    Properties:
      MinCapacity: 1
      MaxCapacity: 2
      ResourceId: !Join ['/', [service, !Ref Cluster, !GetAtt ServiceBatch.Name]]
      RoleARN: !GetAtt ServiceAutoscalingRole.Arn
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
  ServiceScalingPolicyBatch:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub '${ProjectName}-${ENV}-asg-policy-batch'
      ScalingTargetId: !Ref ServiceScalingTargetBatch
      PolicyType: TargetTrackingScaling
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ALBRequestCountPerTarget
          ResourceLabel: !Join ['/', [!GetAtt ALB.LoadBalancerFullName, !GetAtt ALBTargetGroupBatch.TargetGroupFullName]]
        TargetValue: 1000
        ScaleInCooldown: 30
        ScaleOutCooldown: 30
  InvokeApiDestinationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${ProjectName}-${ENV}-InvokeApiDestinationRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'events.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub '${ProjectName}-${ENV}-InvokeApiDestinationPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'events:InvokeApiDestination'
                Resource: '*'
  RuleConnection:
    Type: AWS::Events::Connection
    DependsOn: ALB
    Properties:
      Name: !Sub '${ProjectName}-${ENV}-connection'
      AuthorizationType: API_KEY
      AuthParameters:
        ApiKeyAuthParameters:
          ApiKeyName: x-api-key
          ApiKeyValue: !Join [ '', [ '{{resolve:secretsmanager:', !Ref Secret, ':SecretString:key}}' ] ]
  RuleApiDestination:
    Type: AWS::Events::ApiDestination
    DependsOn: RuleConnection
    Properties:
      Name: !Sub '${ProjectName}-${ENV}-api-destination'
      ConnectionArn: !GetAtt RuleConnection.Arn
      HttpMethod: POST
      InvocationEndpoint: !Join [ '/', ['https:/', !GetAtt ALB.DNSName, '*' ] ]
      InvocationRateLimitPerSecond: 300

#Outputs:
#  ALBDNSName:
#    value: !Join [ '/', ['https:/', !GetAtt ALB.DNSName, '*' ] ]
#    Export:
#      Name: !Sub '${ProjectName}-${ENV}-ALBDNSName'
#  APIKey:
#    value: !Join [ '', [ '{{resolve:secretsmanager:', !Ref Secret, ':SecretString:key}}' ] ]
#    Export:
#      Name: !Sub '${ProjectName}-${ENV}-APIKey'