server:
  port: 8081  # API(8080)와 다른 포트 사용
spring:
  profiles:
    active: dev
  application:
    name: batch
  config:
    import:
      - "classpath:application-core.yaml"
      - "classpath:application-batch.yaml"